config/routes.rb
Rails.application.routes.draw do
  resources :lines
  resources :organizations do
    resources :departaments do
      resources :units
    end
  end
  root 'organizations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/departament.rb
class Departament < ApplicationRecord
  belongs_to :organization
  has_many :units, dependent: :destroy
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :departaments, dependent: :destroy
  has_many :units
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :organization
  belongs_to :departament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def organization
      @organization ||= Organization.find(params[:organization_id])
    end

    helper_method :organization

    def departament
      @departament ||= organization.departaments.find(params[:departament_id])
    end

    helper_method :departament
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    if departaments.create(departament_params)
      redirect_to organization_departaments_path(organization)
    end
  end

  def edit
  end

  def update
    if departament.update(departament_params)
      redirect_to organization_departaments_path(organization)
    end
  end

  def destroy
    if departament.destroy
      redirect_to organization_departaments_path(organization)
    end
  end

  private 
    def departament_params
      params.require(:departament).permit(:departament_name, :departament_description)
    end

    def departaments
      @departaments ||= organization.departaments
    end
    helper_method :departaments

    def departament
      @departament ||= departaments.find(params[:id])
    end

    helper_method :departament
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @lines = Line.all
  end

  def new
  end

  def create
    if @line = Line.create(line_params)
      redirect_to lines_path
    end
  end

  def edit
    if @line = Line.find(params[:id])
    end
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(line_params)
      redirect_to lines_path
    end
  end

  def destroy
    @line = Line.find(params[:id])
    if @line.destroy
      redirect_to lines_path
    end
  end

  private
    def line_params
      params.require(:line).permit(:rec)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def show
  end

  def new
  end

  def create
    @organization = Organization.new(organization_params)
 
    if @organization.save
      redirect_to organizations_path
    end
  end

  def edit
  end

  def update
    if organization.update(organization_params)
      redirect_to organizations_path
    end
  end

  def destroy
    if organization.destroy
      redirect_to organizations_path
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :address, :phone, :email)
  end

  def organization
    @organization ||= Organization.find(params[:id])
  end
  helper_method :organization
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    @unit.organization = organization
    @unit.departament = departament
    if @unit.save
      redirect_to organization_departament_units_path(organization, departament.id)
    end
  end

  def edit
  end

  def update
    if unit.update(unit_params)
      redirect_to organization_departament_units_path(organization, departament.id)
    end
  end

  def destroy
    if unit.destroy
      redirect_to organization_departament_units_path(organization, departament.id)
    end
  end

  private
  def unit_params
    params.require(:unit).permit(:full_name)
  end

  def units
    @units ||= departament.units
  end
  helper_method :units

  def unit
    @unit ||= departament.units.find(params[:id])
  end
  helper_method :unit
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/departaments/edit.html.haml
.panel.panel-primary
  .panel-heading
    EDIT
  .panel-body
    = bootstrap_form_for departament, url: organization_departament_path([organization, departament]) do |f|
      = f.text_field :departament_name
      = f.text_area :departament_description
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organization_departaments_path(organization), :type=> "button", :class => "btn btn-danger"

app/views/departaments/index.html.haml
.navbar.navbar-default{:role=>"navigation"}>
  .container-fluid
    .navbar-header
      .navbar-brand 
        This all departaments of 
        = organization.name
        company
    .collapse.navbar-collapse
    #bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to 'ALL COMPANIES', organizations_path()
      %li= link_to 'MY COMPANY', organization_path(id: organization.id)
      %li= link_to 'NEW DEPARTAMENT', new_organization_departament_path(), :type=> "button", :class => "btn btn-default"
%table.table
  %tr
    %th Departament id
    %th Departament name
    %th Departament description
    %th Organization id
    %th{:colspan => "4"} Actions
    - departaments.each do |departament|
      %tr
        %td= departament.id
        %td= departament.departament_name
        %td= departament.departament_description
        %td= departament.organization_id
        %td= link_to 'Units', organization_departament_units_path(departament.organization_id, departament.id)
        %td= link_to 'Details', organization_departament_path(departament.organization_id, departament.id)
        %td= link_to 'Edit', edit_organization_departament_path(departament.organization_id, departament.id)
        %td= link_to 'Delete departament', organization_departament_path(departament.organization_id, departament.id), method: :delete

app/views/departaments/new.html.haml
.panel.panel-primary
  .panel-heading
    NEW
  .panel-body
    =bootstrap_form_for :departament, url: organization_departaments_path(organization) do |f|
      = f.text_field :departament_name
      = f.text_area :departament_description
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organization_departaments_path(organization), :type=> "button", :class => "btn btn-danger"

app/views/organizations/edit.html.haml
.panel.panel-primary
  .panel-heading
    EDIT
  .panel-body
    = bootstrap_form_for organization, url: organization_path(organization), method: :patch do |f|
      = f.text_field :name
      = f.text_field :address
      = f.text_field :phone
      = f.text_field :email
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organizations_path(), :type=> "button", :class => "btn btn-danger"

app/views/organizations/index.html.haml
.row
  .col-md-8
    .navbar.navbar-default{:role=>"navigation"}>
      .container-fluid
        .navbar-header
          .navbar-brand 
            Create you list you company stucrure by us
        .collapse.navbar-collapse
        #bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          %li= link_to 'FIRST LINES', lines_path
          %li= link_to 'ADD COMPANY', new_organization_path(), :type=> "button", :class => "btn btn-default"
  .col-md-4
    .page-header
      %h3 Try create contact book with rails
      %small using rails and bootstrap
.row
  .col-md-4
    .panel.panel-success
      .panel-heading
        %h4 Here is all companies
      %ul.list-group
      - @organizations.each do |organization|
        %li.list-group-item
          = link_to 'Remove', organization_path(organization), method: :delete, :class => 'btn btn-danger'
          = link_to 'edit', edit_organization_path(organization), :class => 'btn btn-warning'
          = link_to organization.name, organization_path(organization), :class => 'btn btn-success'
  .col-md-8

app/views/organizations/new.html.haml
.panel.panel-primary
  .panel-heading
    NEW
  .panel-body
    = bootstrap_form_for :organization, url: organizations_path do |f|
      = f.text_field :name
      = f.text_field :address
      = f.text_field :phone
      = f.text_field :email
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organizations_path(), :type=> "button", :class => "btn btn-danger"

app/views/organizations/show.html.haml
.navbar.navbar-default{:role=>"navigation"}>
  .container-fluid
    .navbar-header
      .navbar-brand 
        Contact information of
        = organization.name
        company
    .collapse.navbar-collapse
    #bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to 'ALL COMPANIES', organizations_path()
      %li= link_to 'DEPARTAMENTS', organization_departaments_path(organization)
= organization.name
= organization.address
= organization.phone
= organization.email

app/views/personals/new.html.haml
= form_for :personal, url: organization_departament_personals_path(@organization, @departament) do |f|
  = f.text_field :full_name
  = f.submit

app/views/units/_1.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/units/edit.html.haml
.panel.panel-primary
  .panel-heading
    EDIT
  .panel-body
    = bootstrap_form_for unit, url: organization_departament_unit_path(organization, departament, unit) do |f|
      = f.text_field :full_name
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organization_departament_units_path(organization), :type=> "button", :class => "btn btn-danger"

app/views/units/index.html.haml
.navbar.navbar-default{:role=>"navigation"}>
  .container-fluid
    .navbar-header
      .navbar-brand 
        This all units of 
        = departament.departament_name
        departament
    .collapse.navbar-collapse
    #bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to 'ALL COMPANIES', organizations_path()
      %li= link_to 'MY COMPANY', organization_path(id: organization.id)
      %li= link_to 'DEPARTAMENTS', organization_departaments_path()
      %li= link_to 'ADD UNIT', new_organization_departament_unit_path(), :type=> "button", :class => "btn btn-default"
%table.table
  %tr
    %th Unit name
    %th{:colspan=>"3"} Action
  - units.each do |unit|
    %tr
      %td= unit.full_name
      %td= link_to 'detail', organization_departament_unit_path(id: unit.id)
      %td= link_to 'edit', edit_organization_departament_unit_path(id: unit.id)
      %td= link_to 'destroy', organization_departament_unit_path(id: unit.id), method: :delete
/ = render "1.html.erb"

app/views/units/new.html.haml
.panel.panel-primary
  .panel-heading
    CREATE
  .panel-body
    = bootstrap_form_for @unit, url: organization_departament_units_path(:organization_id => organization.id, :departament_id => departament.id) do |f|
      = f.text_field :full_name
      = f.submit :class => "btn btn-primary"
      = link_to 'CANCEL', organization_departament_units_path(organization), :type=> "button", :class => "btn btn-danger"

app/views/units/show.html.haml
.navbar.navbar-default{:role=>"navigation"}>
  .container-fluid
    .navbar-header
      .navbar-brand 
        Detail information about 
        = unit.full_name
    .collapse.navbar-collapse
    #bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to 'ALL COMPANIES', organizations_path()
      %li= link_to 'MY COMPANY', organization_path(id: organization.id)
      %li= link_to 'DEPARTAMENTS', organization_departaments_path()
      %li= link_to 'ALL UNITS', organization_departament_units_path()
%table.table
  %tr
    %th Id
    %th Full name
  %tr
    %td= unit.id
    %td= unit.full_name